
services:
  - type: web
    name: shemoves-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: E3vuNo5OvRMKQ6nVmaIHsnZ1FEtwrpAT
      - key: DATABASE_URL
        value: postgresql://shemoves_db_user:E3vuNo5OvRMKQ6nVmaIHsnZ1FEtwrpAT@dpg-d0ptleodl3ps73b4efkg-a.oregon-postgres.render.com/shemoves_db
      - key: RENDER
        value: true
    plan: free
    autoDeploy: true
